# Samsung modemctl driver has issues when built with 
# 2011.03 toolchain, so this driver isn't being built
# anymore. It was changed by the binary driver built
# with 2009q03 toolchain.
#
# BEFORE kernel compilation, one should enter in this
# directory and run 'make'.
#
# Thanks to alterbridge86.
all:
	cp samsung_modemctl_built-in_2009q03 built-in.o
